# Generated by Django 5.1 on 2024-08-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
