# Generated by Django 5.1 on 2024-08-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
